# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: docker
on:
  push:
    tags: "*.*.*"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: zymlabs/doris.k8s-operator

      - name: Doris Debug meta
        id: debug_meta
        uses: docker/metadata-action@v5
        with:
          images: zymlabs/doris-debug-ubuntu

      - name: env 
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          Version: ${{ steps.vars.outputs.tag }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.CONTAINER_REGISTRY }}/${{ secrets.CONTAINER_REGISTRY_ORGANIZATION }}/doris.k8s-operator:latest
      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          Version: ${{ steps.vars.outputs.tag }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.CONTAINER_REGISTRY }}/${{ secrets.CONTAINER_REGISTRY_ORGANIZATION }}/doris.k8s-operator:${GITHUB_REF#refs/*/}
      # - name: Build debug and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: Dockerfile_doris_debug
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: ${{ secrets.CONTAINER_REGISTRY }}/${{ steps.debug_meta.outputs.tags }}